### ISSUE TITLE
Distributed DNS record reconciliation

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/dns-operator#14]
# Tasks

## Kuadrant-operator changes
- [ ] Kuadrant/kuadrant-operator#452
- [ ] Kuadrant/kuadrant-operator#453
- [ ] Kuadrant/dns-operator#42

## DNS Operator changes
- [ ] Kuadrant/dns-operator#33
- [ ] Kuadrant/dns-operator#34
- [ ] Kuadrant/dns-operator#35
- [ ] Kuadrant/dns-operator#36
- [ ] Kuadrant/dns-operator#38
- [ ] Kuadrant/kuadrant-operator#454
- [ ] Kuadrant/dns-operator#40

# Testing

- [ ] e2e test for single cluster (no cluster id)
- [ ] e2e test from no cluster id single cluster to cluster ids and shared hosts (IE single to multi-cluster migration)
- [ ] e2e test to go from multi-cluster to single cluster

# Docs

- [ ] Setting up a single cluster (installation)
- [ ] Setting up multi-cluster (installation)
- [ ] Quick Start Walkthroughs
- [ ] Moving between single to multi-cluster
- [ ] Moving between routingStrategies
- [ ] Clean up (Multi-Cluster)

**Comment by maleck13** [comment]
@pehala who is a good person to work alongside @philbrookes  on this issue to help flesh out test plans and start on implementing the needed changes

**Comment by maleck13** [comment]
duplicate
