### ISSUE TITLE
Remove ManagedZone API

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/dns-operator#166]
**What**

Originally ManagedZone was thought of in the context of multiple tenants where we might control the credentals and the zones. This is no longer the case. ManagedZone as remained in place largely as a reference to a credential to the underlying DNS provider. We do not need this indirection. Additionally the ManagedZone API adds some confusion around what should happen when you delete a managed zone resource.

**How**

Remove the ManagedZone resource and update DNSPolicy to use a provider ref to define a specific secret in that namespace.  The dns record controller will propagate this secret to the DNS Record.

These changes to DNS Operator will break kuadrant-operator, so have both PRs ready and approved, before merging the DNS Operator changes.

- [x] [Create RFC](https://github.com/Kuadrant/architecture/issues/67) https://github.com/Kuadrant/architecture/pull/93
- [x] Propagate secret to DNS Records
- [x] Update DNS Operator to read secret directly
- [x] Remove all references to ManagedZone in both DNS Operator and kuadrant-operator
- [x] Update all existing documentation in both DNS Operator and kuadrant-operator
- [x] Update existing tests in both DNS Operator and kuadrant-operator
- [x] Update local-setup in both DNS Operator and kuadrant-operator
- [x] Update makefile commands in both DNS Operator and kuadrant-operator
- [ ] Bump API version to v1alpha2: DNS Record and DNS Policy

See also https://github.com/Kuadrant/multicluster-gateway-controller/issues/406

**Comment by maleck13** [comment]
@mikenairn would appreciate any addiitional thoughts you have on this one.

**Comment by maleck13** [comment]
https://github.com/Kuadrant/kuadrant-operator/pull/793
