### ISSUE TITLE
Review E2E Test Suite

### ISSUE THREAD

**Issue by mikenairn** [Kuadrant/dns-operator#46]
**What**

Add an e2e test suite that exercises the creation of different dnsrecords  (single, multicluster, simple, loadbalanced etc..) and verifies they are created as expected in all the currently supported providers.

**How**

We can do this in a few stages, first we can just add the same basic [e2e test suite](https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/test/e2e/suite_test.go) and [workflow](https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/.github/workflows/ci-e2e.yaml) that we already have in MGC. This will need to be adapted to get rid of all the OCM/Gateway related stuff and only create DNSRecord resources. Initially this can also just do the same Get request check to see that the endpoint is accessible.

Follow on tasks should then look to actually check that the records created in the providers is as expected based on the contents of the DNSRecord resource and also run tests in a simulated multi cluster environment.

At a minimum our test suite should cover the following scenarios:

**_Simple (Single Cluster)_**

* https://github.com/Kuadrant/dns-operator/tree/multicluster_external_dns/hack/dnsrecords/simple

_**LoadBalanced (Single Cluster)**_

* https://github.com/Kuadrant/dns-operator/tree/multicluster_external_dns/hack/dnsrecords/loadbalanced

_**Simple (Multi Cluster with control plane)**_

* https://github.com/Kuadrant/dns-operator/tree/multicluster_external_dns/hack/dnsrecords/simple/combined

_**LoadBalanced (Multi Cluster with control plane)**_

* https://github.com/Kuadrant/dns-operator/tree/multicluster_external_dns/hack/dnsrecords/loadbalanced/combined

_**Simple (Multi Cluster no control plane)**_

Apply all of these at the same time:
* https://github.com/Kuadrant/dns-operator/tree/multicluster_external_dns/hack/dnsrecords/simple

_**LoadBalanced (Multi Cluster no control plane)**_

Apply all of these at the same time:
* https://github.com/Kuadrant/dns-operator/tree/multicluster_external_dns/hack/dnsrecords/loadbalanced

_**Conflicting strategies (simple and loadbalanced)**_

* https://github.com/Kuadrant/dns-operator/tree/multicluster_external_dns/hack/dnsrecords/conflicting

Test script [here](https://github.com/Kuadrant/dns-operator/blob/multicluster_external_dns/hack/test-multicluster.sh) shows how these can be run manually.

**Tasks**

- [x] #51
- [x] Updated e2e test suite to verify provider contents
- [x] Add simple dnsrecord tests (single and multicluster with control plane)  
- [x] Add loadbalanced dnsrecord tests (single and multicluster with control plane  
- [x] Add loadbalanced dnsrecord tests (single and multicluster no control plane)
- [x] Add conflicting dnsrecord tests

**Comment by maleck13** [comment]
@mikenairn The open items here, are they still outstanding (IE need to be done)?
